catalog: maven_market_uc

schemas:
  bronze: bronze
  silver: silver
  gold: gold
  audit: audit

sources:
  adls:
    base_path: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net"
    csv_transactions: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/landing/batch/transactions/"
    csv_regions: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/landing/batch/regions/"
    csv_calender: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/landing/batch/calender/"
    csv_stores: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/landing/batch/stores/"
    csv_returns: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/landing/batch/returns/"

  mongodb:
    uri_secret_scope: "maven_scope"
    uri_secret_key: "maven-mongo-uri"
    database: "maven_market_db"
    collections:
      - name: "products"
        table_key: "bronze_products"
      - name: "customers"
        table_key: "bronze_customers"

  kafka:
    bootstrap_servers: "pkc-w77k7w.centralus.azure.confluent.cloud:9092"
    secret_scope: "maven_scope"
    api_key_name: "kafka-api-key"
    api_secret_name: "kafka-api-secret"
    streams:
      - topic: "maven_orders"
        target_table: "maven_market_uc.bronze.raw_kafka_orders"
        checkpoint_location: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/checkpoints/kafka_orders"
      - topic: "maven_inventory"
        target_table: "maven_market_uc.bronze.raw_kafka_inventory"
        checkpoint_location: "abfss://mavenmarket@sgmarketmaven.dfs.core.windows.net/checkpoints/kafka_inventory"

tables:
  # Bronze Layer (Already configured)
  bronze_customers: "${catalog}.bronze.raw_customers"
  bronze_products: "${catalog}.bronze.raw_products"
  bronze_transactions: "${catalog}.bronze.raw_transactions"
  bronze_kafka_orders: "${catalog}.bronze.raw_kafka_orders"
  bronze_kafka_inventory: "${catalog}.bronze.raw_kafka_inventory"
  bronze_stores: "maven_market_uc.bronze.stores"
  bronze_calendar: "maven_market_uc.bronze.calender"

  # Silver Layer
  silver_customers_scd2: "${catalog}.silver.customers_scd2"
  silver_products: "${catalog}.silver.cleansed_products"
  silver_transactions: "${catalog}.silver.cleansed_transactions"
  silver_orders: "${catalog}.silver.cleansed_orders"
  silver_inventory: "${catalog}.silver.cleansed_inventory"
  silver_stores: "${catalog}.silver.cleansed_stores"
  silver_calendar: "${catalog}.silver.cleansed_calendar"

  # Gold Layer
  gold_fact_sales: "${catalog}.gold.fact_sales"
  gold_dim_customers: "${catalog}.gold.dim_customers"
  gold_dim_products: "${catalog}.gold.dim_products"
  gold_dim_stores: "${catalog}.gold.dim_stores"

expectations:
  transactions:
    valid_quantity: "quantity > 0"
  orders:
    valid_order_id: "order_id IS NOT NULL"
    valid_quantity: "quantity > 0"
  inventory:
    valid_stock: "stock_level >= 0"
  customers:
    valid_email: "email LIKE '%@%'"